name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: perform npm installations
        run: npm install
      - name: lint the code
        run: npm run eslint
      - name: tests
        run: npm run test
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - run: yarn
      - run: expo publish --release-channel production